/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.luxoboy.collectionmanager.view;

import javax.swing.JFrame;

/**
 *
 * @author thiba_000
 */
public class BackButton extends javax.swing.JPanel {

    private DetailsBase detailbase;
    private MainFrame mainFrame;
    
    /**
     * Creates new form BackButton
     */
    public BackButton()
    {
        super();
        initComponents();
    }

    public void setDetailbase(DetailsBase detailbase) {
        this.detailbase = detailbase;
    }

    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        backButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(backButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if(detailbase instanceof TVShowDetails)
        {
            mainFrame.goToSearch();
        }
        else if(detailbase instanceof SeasonDetails)
        {
            mainFrame.goToTVShowDetails();
        }
        else if(detailbase instanceof EpisodeDetails)
        {
            mainFrame.goToSeasonDetails();
        }
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    // End of variables declaration//GEN-END:variables
}
