/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luxoboy.collectionmanager.view;

import com.luxoboy.collectionmanager.api.model.TVShow;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author orann
 */
public class Details extends javax.swing.JPanel {
    
    private JFrame parent;

    /**
     * Creates new form Details
     */
    public Details(JFrame parent) {
        this.parent = parent;       
        initComponents();
    }
    
    public void updateInformations(TVShow tv){
        this.name.setText(tv.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        informationPanel = new javax.swing.JPanel();
        picturePanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        numberOfSeason = new javax.swing.JLabel();
        numberOfSeasonValue = new javax.swing.JLabel();
        yearValue = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        rateValue = new javax.swing.JLabel();
        descriptionPanel = new javax.swing.JPanel();
        description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        ImageIcon backButtonImage = new ImageIcon("Back-Button.png");
        backButton = new javax.swing.JButton(backButtonImage);

        setLayout(new java.awt.GridBagLayout());

        informationPanel.setLayout(new java.awt.GridBagLayout());

        picturePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        informationPanel.add(picturePanel, gridBagConstraints);

        infoPanel.setLayout(new java.awt.GridBagLayout());

        name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        name.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        infoPanel.add(name, gridBagConstraints);

        year.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        year.setText("Year :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        infoPanel.add(year, gridBagConstraints);

        numberOfSeason.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        numberOfSeason.setText("Number of season : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        infoPanel.add(numberOfSeason, gridBagConstraints);

        numberOfSeasonValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        numberOfSeasonValue.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        infoPanel.add(numberOfSeasonValue, gridBagConstraints);

        yearValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        yearValue.setText("00/00/00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(yearValue, gridBagConstraints);

        rate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rate.setText("Rate :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(rate, gridBagConstraints);

        rateValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rateValue.setText("0/10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(rateValue, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        informationPanel.add(infoPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        add(informationPanel, gridBagConstraints);

        descriptionPanel.setLayout(new java.awt.GridBagLayout());

        description.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        description.setText("Description :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        descriptionPanel.add(description, gridBagConstraints);

        descriptionText.setColumns(20);
        descriptionText.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        descriptionText.setRows(5);
        descriptionText.setEnabled(false);
        jScrollPane1.setViewportView(descriptionText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        descriptionPanel.add(jScrollPane1, gridBagConstraints);

        addButton.setText("Add to my Collection");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        descriptionPanel.add(addButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(descriptionPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        backButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        buttonPanel.add(backButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(buttonPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);        
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel description;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel numberOfSeason;
    private javax.swing.JLabel numberOfSeasonValue;
    private javax.swing.JPanel picturePanel;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel rateValue;
    private javax.swing.JLabel year;
    private javax.swing.JLabel yearValue;
    // End of variables declaration//GEN-END:variables
}
