/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.luxoboy.collectionmanager.view;

import java.util.ArrayList;
import javax.swing.JRadioButton;

/**
 *
 * @author thiba_000
 */
public class RateBar extends javax.swing.JPanel {

    private ArrayList<JRadioButton> rateBar;
    private int rate;
    /**
     * Creates new form RateBar
     */
    public RateBar() {
        initComponents();
        this.rateBar = new ArrayList<>();
        rateBar.add(note1);
        rateBar.add(note2);
        rateBar.add(note3);
        rateBar.add(note4);
        rateBar.add(note5);
        rateBar.add(note6);
        rateBar.add(note7);
        rateBar.add(note8);
        rateBar.add(note9);
        rateBar.add(note10);
    }
    
    /**
     * Update the selection of the radio button for the rate bar
     * @param rate
     */
    public void updateRadionButtonRate(int rate){
        for(int j = 0; j < rateBar.size(); j++){
            if(j < rate){
                rateBar.get(j).setSelected(true);
            }else{
                rateBar.get(j).setSelected(false);
            }
        }
        this.rate = rate;
    }
    
    
    /**
     * Return the rate
     * @return rate
     */
    public int getRate(){
        return this.rate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rateLabel = new javax.swing.JLabel();
        note1 = new javax.swing.JRadioButton();
        note2 = new javax.swing.JRadioButton();
        note3 = new javax.swing.JRadioButton();
        note4 = new javax.swing.JRadioButton();
        note5 = new javax.swing.JRadioButton();
        note6 = new javax.swing.JRadioButton();
        note7 = new javax.swing.JRadioButton();
        note8 = new javax.swing.JRadioButton();
        note9 = new javax.swing.JRadioButton();
        note10 = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        rateLabel.setText("Rate :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(rateLabel, gridBagConstraints);

        note1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note1, gridBagConstraints);

        note2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note2, gridBagConstraints);

        note3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note3, gridBagConstraints);

        note4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note4, gridBagConstraints);

        note5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note5, gridBagConstraints);

        note6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note6, gridBagConstraints);

        note7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note7, gridBagConstraints);

        note8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note8, gridBagConstraints);

        note9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note9, gridBagConstraints);

        note10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(note10, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void note1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note1ActionPerformed
        updateRadionButtonRate(1);
    }//GEN-LAST:event_note1ActionPerformed

    private void note2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note2ActionPerformed
        updateRadionButtonRate(2);
    }//GEN-LAST:event_note2ActionPerformed

    private void note3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note3ActionPerformed
        updateRadionButtonRate(3);
    }//GEN-LAST:event_note3ActionPerformed

    private void note4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note4ActionPerformed
        updateRadionButtonRate(4);
    }//GEN-LAST:event_note4ActionPerformed

    private void note5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note5ActionPerformed
        updateRadionButtonRate(5);
    }//GEN-LAST:event_note5ActionPerformed

    private void note6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note6ActionPerformed
        updateRadionButtonRate(6);
    }//GEN-LAST:event_note6ActionPerformed

    private void note7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note7ActionPerformed
        updateRadionButtonRate(7);
    }//GEN-LAST:event_note7ActionPerformed

    private void note8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note8ActionPerformed
        updateRadionButtonRate(8);
    }//GEN-LAST:event_note8ActionPerformed

    private void note9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note9ActionPerformed
        updateRadionButtonRate(9);
    }//GEN-LAST:event_note9ActionPerformed

    private void note10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note10ActionPerformed
        updateRadionButtonRate(10);
    }//GEN-LAST:event_note10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton note1;
    private javax.swing.JRadioButton note10;
    private javax.swing.JRadioButton note2;
    private javax.swing.JRadioButton note3;
    private javax.swing.JRadioButton note4;
    private javax.swing.JRadioButton note5;
    private javax.swing.JRadioButton note6;
    private javax.swing.JRadioButton note7;
    private javax.swing.JRadioButton note8;
    private javax.swing.JRadioButton note9;
    private javax.swing.JLabel rateLabel;
    // End of variables declaration//GEN-END:variables
}
