/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luxoboy.collectionmanager.view;

import java.util.Date;
import javax.swing.AbstractListModel;

/**
 *
 * @author orann
 */
public class UserCollection extends javax.swing.JPanel {

    /**
     * Creates new form List
     */
    public UserCollection() {
        initComponents();
    }
    
    public void initView(String name, Date date, int numberOfSeason){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollList = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        detailPanel = new javax.swing.JPanel();
        informationsPanel = new javax.swing.JPanel();
        picturePanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        numberOfSeason = new javax.swing.JLabel();
        numberOfSeasonValue = new javax.swing.JLabel();
        yearValue = new javax.swing.JLabel();
        descriptionPanel = new javax.swing.JPanel();
        description = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        reviewPanel = new javax.swing.JPanel();
        review = new javax.swing.JLabel();
        reviewScroll = new javax.swing.JScrollPane();
        reviewTextArea = new javax.swing.JTextArea();
        ratePanel = new javax.swing.JPanel();
        rate = new javax.swing.JLabel();
        note1 = new javax.swing.JRadioButton();
        note2 = new javax.swing.JRadioButton();
        note3 = new javax.swing.JRadioButton();
        note4 = new javax.swing.JRadioButton();
        note5 = new javax.swing.JRadioButton();
        removeButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        scrollList.setViewportView(list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(scrollList, gridBagConstraints);

        detailPanel.setLayout(new java.awt.GridBagLayout());

        informationsPanel.setLayout(new java.awt.GridBagLayout());

        picturePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        informationsPanel.add(picturePanel, gridBagConstraints);

        infoPanel.setLayout(new java.awt.GridBagLayout());

        name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        name.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(name, gridBagConstraints);

        year.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        year.setText("Year :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(year, gridBagConstraints);

        numberOfSeason.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        numberOfSeason.setText("Number of season :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(numberOfSeason, gridBagConstraints);

        numberOfSeasonValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        numberOfSeasonValue.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(numberOfSeasonValue, gridBagConstraints);

        yearValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        yearValue.setText("00/00/0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        infoPanel.add(yearValue, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        informationsPanel.add(infoPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        detailPanel.add(informationsPanel, gridBagConstraints);

        descriptionPanel.setLayout(new java.awt.GridBagLayout());

        description.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        description.setText("Description :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        descriptionPanel.add(description, gridBagConstraints);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setEnabled(false);
        scrollPane.setViewportView(descriptionTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        descriptionPanel.add(scrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        detailPanel.add(descriptionPanel, gridBagConstraints);

        reviewPanel.setLayout(new java.awt.GridBagLayout());

        review.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        review.setText("Review :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        reviewPanel.add(review, gridBagConstraints);

        reviewTextArea.setColumns(20);
        reviewTextArea.setRows(5);
        reviewScroll.setViewportView(reviewTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        reviewPanel.add(reviewScroll, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        detailPanel.add(reviewPanel, gridBagConstraints);

        ratePanel.setLayout(new java.awt.GridBagLayout());

        rate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rate.setText("Rate :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        ratePanel.add(rate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        ratePanel.add(note1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        ratePanel.add(note2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        ratePanel.add(note3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        ratePanel.add(note4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        ratePanel.add(note5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        detailPanel.add(ratePanel, gridBagConstraints);

        removeButton.setText("Remove");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        detailPanel.add(removeButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(detailPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
        
    }//GEN-LAST:event_listValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel informationsPanel;
    private javax.swing.JList list;
    private javax.swing.JLabel name;
    private javax.swing.JRadioButton note1;
    private javax.swing.JRadioButton note2;
    private javax.swing.JRadioButton note3;
    private javax.swing.JRadioButton note4;
    private javax.swing.JRadioButton note5;
    private javax.swing.JLabel numberOfSeason;
    private javax.swing.JLabel numberOfSeasonValue;
    private javax.swing.JPanel picturePanel;
    private javax.swing.JLabel rate;
    private javax.swing.JPanel ratePanel;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel review;
    private javax.swing.JPanel reviewPanel;
    private javax.swing.JScrollPane reviewScroll;
    private javax.swing.JTextArea reviewTextArea;
    private javax.swing.JScrollPane scrollList;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel year;
    private javax.swing.JLabel yearValue;
    // End of variables declaration//GEN-END:variables
}
