/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author orann
 */
public class Details extends javax.swing.JPanel {

    /**
     * Creates new form Details
     */
    public Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        informationPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        numberOfSeason = new javax.swing.JLabel();
        numberOfSeasonValue = new javax.swing.JLabel();
        descriptionPanel = new javax.swing.JPanel();
        description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        informationPanel.setLayout(new java.awt.GridBagLayout());

        name.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        name.setText("name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        informationPanel.add(name, gridBagConstraints);

        year.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        year.setText("year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        informationPanel.add(year, gridBagConstraints);

        photo.setText("photo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        informationPanel.add(photo, gridBagConstraints);

        numberOfSeason.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        numberOfSeason.setText("number of season : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        informationPanel.add(numberOfSeason, gridBagConstraints);

        numberOfSeasonValue.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        numberOfSeasonValue.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        informationPanel.add(numberOfSeasonValue, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        add(informationPanel, gridBagConstraints);

        descriptionPanel.setLayout(new java.awt.GridBagLayout());

        description.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        description.setText("description :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        descriptionPanel.add(description, gridBagConstraints);

        descriptionText.setColumns(20);
        descriptionText.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        descriptionText.setRows(5);
        jScrollPane1.setViewportView(descriptionText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        descriptionPanel.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(descriptionPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel numberOfSeason;
    private javax.swing.JLabel numberOfSeasonValue;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
